#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER "${POSTGRES_NORMAL_USER}" WITH PASSWORD '${POSTGRES_NORMAL_USER_PASSWORD}';
	GRANT ALL PRIVILEGES ON DATABASE "${POSTGRES_DB}" TO "${POSTGRES_NORMAL_USER}";
	GRANT ALL ON SCHEMA public TO "${POSTGRES_NORMAL_USER}";
EOSQL
